# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='location',
            field=models.CharField(default='Gym X', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
