# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20170625_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(default=None, null=True)),
                ('weight', models.IntegerField(default=None, null=True)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Excercise')),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.Workout')),
            ],
        ),
    ]
