# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_auto_20171119_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='workout_rank',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
