# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20171125_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='workout_rank',
            new_name='workout_order',
        ),
        migrations.AddField(
            model_name='set',
            name='done',
            field=models.BooleanField(default=0),
        ),
    ]
