# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_auto_20171126_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinesection',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='routinesection',
            name='section',
        ),
        migrations.AddField(
            model_name='routine',
            name='plan',
            field=models.ManyToManyField(to='gym.Plan'),
        ),
        migrations.DeleteModel(
            name='RoutineSection',
        ),
    ]
