# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20171129_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='routineplan',
            name='routine',
        ),
        migrations.AddField(
            model_name='excercise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='excercise',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='routine',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.MuscleGroup'),
        ),
        migrations.AddField(
            model_name='section',
            name='random',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='set',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workout',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='excercise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.Excercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='RoutinePlan',
        ),
    ]
