# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_auto_20171129_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='random',
            new_name='random_excercise',
        ),
        migrations.AddField(
            model_name='section',
            name='random_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='type',
            field=models.CharField(choices=[('EF', 'Excercise first'), ('SF', 'Set first'), ('AT', 'Alternate two'), ('RO', 'Random order')], default='AT', max_length=2),
        ),
    ]
