# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_auto_20171203_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
