# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_auto_20171210_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='set',
            name='excercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.Excercise'),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
