# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_auto_20171212_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='lever',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='mass_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
