# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_auto_20171228_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Workout X', max_length=100),
        ),
    ]
