# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-11 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170411_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date_published'),
        ),
    ]
