# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-11 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20170411_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gym',
        ),
    ]
