# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-22 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20170421_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sets',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='section',
            name='target',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
