# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_plan_rndprogram_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='plan',
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('SS', 'Superset'), ('SF', 'Set first'), ('EF', 'Excercise first'), ('', 'Excercise first')], default='EF', max_length=2),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Workout'),
        ),
    ]
