# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_section_excercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Workout'),
        ),
    ]
