# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_section_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='excercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Excercise'),
        ),
    ]
