# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20170421_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='excercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.Excercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.Workout'),
            preserve_default=False,
        ),
    ]
