# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-22 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20170422_0731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Routine',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='workout',
            new_name='routine',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='workout',
            new_name='routine',
        ),
    ]
